env:
ROM_URL:https://www.coolapk.com/link?url=https%3A%2F%2Fdownload.meizu.com%2FFirmware%2FFlyme%2F16s%2F9.21.4.24%2Fcn_daily%2F20210424183518%2F6d1568eb%2Fupdate.zip
ROM_NAME:Flyme
TZ:Asia/Shanghai
